services:
  # Redis Database
  redis-only-cache:
    image: redis:7-alpine
    container_name: redis-only-cache
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1GB
        reservations:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - redis-network

  # Hash Service Instance 1
  redis-only-service-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-only-service-1
    environment:
      - NODE_ENV=development
      - PORT=3000
      - INSTANCE_ID=1
      - REDIS_HOST=redis-only-cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    restart: unless-stopped
    depends_on:
      redis-only-cache:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - redis-network

  # Hash Service Instance 2
  redis-only-service-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-only-service-2
    environment:
      - NODE_ENV=development
      - PORT=3000
      - INSTANCE_ID=2
      - REDIS_HOST=redis-only-cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    restart: unless-stopped
    depends_on:
      redis-only-cache:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - redis-network

  # Hash Service Instance 3
  redis-only-service-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-only-service-3
    environment:
      - NODE_ENV=development
      - PORT=3000
      - INSTANCE_ID=3
      - REDIS_HOST=redis-only-cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    restart: unless-stopped
    depends_on:
      redis-only-cache:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - redis-network

  # Hash Service Instance 4
  redis-only-service-4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-only-service-4
    environment:
      - NODE_ENV=development
      - PORT=3000
      - INSTANCE_ID=4
      - REDIS_HOST=redis-only-cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    restart: unless-stopped
    depends_on:
      redis-only-cache:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - redis-network

  # Nginx Load Balancer
  redis-only-nginx:
    image: nginx:alpine
    container_name: redis-only-nginx
    ports:
      - "8120:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - redis-only-service-1
      - redis-only-service-2
      - redis-only-service-3
      - redis-only-service-4
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
